[CONFIG]
; parameters for sh file
; mode: 'direct' or 'deepensemble'
mode = direct
prueba = test25_tesis
; model_dir can be left empty to use main_path/prueba or specified (e.g. ./kaggle_runs/output/alexnet/alexnet_new)
model_dir = 

[PATHS]
; paths for loading files
main_path = ./csst_catalog/test25_tesis/
test_path = ./csst_catalog/test/
fits_path = ./csst_catalog/fits/
tfrecords_path_train = ./csst_catalog/tfrecords/train/
tfrecords_path_test = ./csst_catalog/tfrecords/test/
csv_file = ./csst_catalog/csst_wf_stack.csv
kaggle_runs_dir = ./kaggle_runs/output/

[MODEL]
; parameters for training and testing
classes = 4
labels = theta_E,f_axis,e1,e2
total_images = 70000
test_images = 6396
learning_rate = 1e-3
channels = 1
num_pix = 100
; delta for pixels in arcseconds/pixel
delta_pix = 0.06
epochs = 50
batch_size = 128
dropouts = 0.0,0.0
train_split = 0.8
val_split = 0.2

[PARALLEL]
cores = 8

[PSNR]
; parameters for single image PSNR comparison
idx = 1727

[SSIM]
; parameters for SSIM analysis
num_samples = 3
ring_width = 0.15

[DEEPENSAMBLE]
n_folds = 5

; parameters when using xgboost
[XGBOOST]
estimators = 100

[INSTRUMENTS]
delta_euclid = 0.1
delta_csst = 0.074
